trigger: none

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-conn'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az mysql flexible-server create --location northeurope --resource-group DB-Flexi-RG --name DBTestFlexiserver1 --admin-user dbuser --admin-password 123456789aA# --sku-name Standard_B1ms --tier Burstable --public-access 0.0.0.0 --storage-size 32 --tags "key=env=dev" --version 5.7 --storage-auto-grow Enabled --iops 500'


    


